### ISSUE TITLE
Is authenticatedUser ever repopulated when setting the accessToken?

### ISSUE THREAD

**Issue by tonyarnold** [joeldev/ADNKit#28]
I might be missing something pretty basic here, but when creating a new `ANKClient` and setting the `accessToken` like so:

``` objective-c
ANKClient *savedClient = [[ANKClient alloc] init];
savedClient.accessToken = [SSKeychain passwordForService:[self keychainServiceName] account:account[kSSKeychainAccountKey]];
```

The `authenticatedUser` property is not repopulated. Is this expected behaviour? Should I be running `fetchCurrentUserWithCompletion:` each time I set the `accessToken`? 

Thanks!

**Comment by joeldev** [comment]
Sorry, I need to do a scrub through the documentation and update a few things (this being one of them). There is a separate method on ANKClient - logInWithAccessToken:completion: that does fetch the current user after setting the token. Directly setting the property does not cause the user to be fetched, which is indeed expected behavior.

**Comment by tonyarnold** [comment]
Ah, righto — I'm guessing this method is in :head?

**Comment by joeldev** [comment]
Yeah - are you using the CocoaPods release? The library is due for another, part of what I have been waiting for is having not updated documentation yet.

**Comment by tonyarnold** [comment]
Yup, and it's all good — updated to head and away we go. Thanks, Joel!
